name: MCC
version: '${project.version}'
author: kotayka_
main: com.kotayka.mcc.mainGame.MCC
api-version: 1.18
depend:
  [ProtocolLib]
commands:
  npc:
    description: Spawn NPC at location
  start:
    description: Start a game
  mccteam:
    description: Teams