name: MCC
version: '${project.version}'
author: kotayka_
main: com.kotayka.mcc.mainGame.MCC
api-version: 1.18
depend:
  [ProtocolLib]
commands:
  npc:
    description: Spawn NPC at location
  start:
    description: Start a game
  mccteam:
    description: Teams
  world:
    description: prints out world
  checkbuild:
    description: Checks the build for BSABM
permissions:
  npc:
    description: Spawn NPC at location
    default: op;
  start:
    description: Start a game
    default: op;
  mccteam:
    description: Teams
  world:
    description: prints out world
    default: op;
  checkbuild:
    description: Checks the build for BSABM
