name: MBC
version: '${project.version}'
main: gg.mbc.EventPlugin
api-version: '26.2'
authors: [ Pengu1n, rspacerr, bigkirbypuff ]
description: Minecraft Bergen Championship
depend: [Citizens, WorldEdit]
commands:
  reload:
    permission: op
    description: reloads the plugin
    usage: /reload [confirm|debug]
  changename:
    description: change or reset your team name
    usage: /teamname change [name]
  debug:
    permission: op
    usage: /debug [criteria]
    description: sends debug messages
  ping:
    description: get a player's ping
    usage: /ping [player]
  changeTeam:
    permission: op
    description: change team of player
    usage: /changeteam [team] [player]